// ui_backup/src/components/modals/CreateKeyModal.tsx
import { useState, useRef } from "preact/hooks";

interface Props {
    modalRef: any;
    onSuccess: (rawKey: string) => void;
}

export default function CreateKeyModal({ modalRef, onSuccess }: Props) {
    const [createMode, setCreateMode] = useState<"prepaid" | "subscription">("prepaid");
    const [createProvider, setCreateProvider] = useState("openai");

    const handleCreateSubmit = async (e: Event) => {
        e.preventDefault();
        const form = e.target as HTMLFormElement;
        const fd = new FormData(form);

        const mode = fd.get("mode_type") as string;
        const days = parseInt(fd.get("expiration") as string);
        let expires_at: number | null = null;
        let period = "none";

        if (mode === "prepaid") {
            if (days > 0) expires_at = Math.floor(Date.now() / 1000) + days * 86400;
        } else {
            period = fd.get("budget_period") as string;
        }

        const provider = fd.get("provider") || "openai";
        const payload = {
            name: fd.get("name"),
            provider: provider,
            expires_at,
            budget_limit: parseFloat(fd.get("budget_limit") as string),
            budget_period: period,
            is_mock: provider === "mock",
            mock_config: fd.get("mock_config"),
            rate_limit: parseInt(fd.get("rate_limit") as string) || 10,
            rate_period: fd.get("rate_period") || "minute",
        };

        try {
            const res = await fetch("/v1/config/app-keys", {
                method: "POST",
                body: JSON.stringify(payload),
                headers: { "Content-Type": "application/json" },
            });

            if (res.ok) {
                const data = await res.json();
                onSuccess(data.key);
                if (modalRef.current) modalRef.current.checked = false;
                form.reset();
                setCreateProvider("openai");
                setCreateMode("prepaid");
            } else {
                alert("Failed to create key");
            }
        } catch (err) {
            console.error("Create error:", err);
        }
    };

    return (
        <>
            <input type="checkbox" id="create-key-modal" class="modal-toggle" ref={modalRef} />
            <div class="modal">
                <div class="modal-box w-11/12 max-w-2xl bg-base-100 border border-white/5 rounded-2xl shadow-2xl p-0 overflow-visible">
                    <div class="p-6 border-b border-white/5 flex justify-between items-center bg-base-200/50 rounded-t-2xl">
                        <div>
                            <h3 class="font-bold text-xl text-white tracking-tight">Generate API Key</h3>
                            <p class="text-xs text-white/40 mt-1">Set usage limits and provider for your new key.</p>
                        </div>
                        <label for="create-key-modal" class="btn btn-sm btn-circle btn-ghost">✕</label>
                    </div>

                    <form id="create-key-form" class="p-6 flex flex-col gap-6" onSubmit={handleCreateSubmit}>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div class="form-control">
                                <label class="label"><span class="label-text font-bold text-white/60 text-[10px] uppercase tracking-widest">Name</span></label>
                                <input type="text" name="name" placeholder="e.g. My App" class="input input-bordered w-full bg-white/5 border-white/5 focus:border-primary/50 rounded-xl" required />
                            </div>
                            <div class="form-control">
                                <label class="label"><span class="label-text font-bold text-white/60 text-[10px] uppercase tracking-widest">Provider</span></label>
                                <select name="provider" class="select select-bordered w-full bg-white/5 border-white/5 rounded-xl text-sm" onChange={(e) => setCreateProvider(e.currentTarget.value)}>
                                    <option value="openai" selected>OpenAI</option>
                                    <option value="mock">Mock</option>
                                    <option value="anthropic" disabled>Anthropic (Soon)</option>
                                </select>
                            </div>
                            <div class="form-control">
                                <label class="label"><span class="label-text font-bold text-white/60 text-[10px] uppercase tracking-widest">Budget Type</span></label>
                                <div class="flex p-1 bg-white/5 rounded-xl border border-white/5">
                                    <button type="button" onClick={() => setCreateMode("prepaid")} class={`flex-1 py-1.5 text-[10px] font-bold tracking-wider rounded-lg transition-all ${createMode === "prepaid" ? 'bg-primary text-white' : 'text-white/40'}`}>ONE-TIME</button>
                                    <button type="button" onClick={() => setCreateMode("subscription")} class={`flex-1 py-1.5 text-[10px] font-bold tracking-wider rounded-lg transition-all ${createMode === "subscription" ? 'bg-primary text-white' : 'text-white/40'}`}>RECURRING</button>
                                    <input type="hidden" name="mode_type" value={createMode} />
                                </div>
                            </div>
                            <div class="form-control">
                                <label class="label"><span class="label-text font-bold text-white/60 text-[10px] uppercase tracking-widest">Limit ($)</span></label>
                                <input type="number" name="budget_limit" defaultValue="5.00" step="0.01" min="0" class="input input-bordered w-full bg-white/5 border-white/5 rounded-xl font-mono" />
                            </div>
                            {createMode === "prepaid" ? (
                                <div class="form-control">
                                    <label class="label"><span class="label-text font-bold text-white/60 text-[10px] uppercase tracking-widest">Expiration</span></label>
                                    <select name="expiration" class="select select-bordered w-full bg-white/5 border-white/5 rounded-xl text-sm">
                                        <option value="7">1 Week</option>
                                        <option value="30">1 Month</option>
                                        <option value="90" selected>3 Months</option>
                                        <option value="0">Indefinite</option>
                                    </select>
                                </div>
                            ) : (
                                <div class="form-control">
                                    <label class="label"><span class="label-text font-bold text-white/60 text-[10px] uppercase tracking-widest">Reset Period</span></label>
                                    <select name="budget_period" class="select select-bordered w-full bg-white/5 border-white/5 rounded-xl text-sm">
                                        <option value="monthly" selected>Monthly</option>
                                        <option value="weekly">Weekly</option>
                                    </select>
                                </div>
                            )}
                            <div class="form-control">
                                <label class="label"><span class="label-text font-bold text-white/60 text-[10px] uppercase tracking-widest">Rate Limit</span></label>
                                <div class="flex flex-row gap-2">
                                    <input type="number" name="rate_limit" defaultValue="10" min="0" class="input input-bordered flex-1 min-w-0 bg-white/5 border-white/5 rounded-xl font-mono" />
                                    <select name="rate_period" class="select select-bordered bg-white/5 border-white/5 rounded-xl text-[10px] font-bold uppercase w-20">
                                        <option value="minute" selected>RPM</option>
                                        <option value="second">RPS</option>
                                        <option value="none">UNLT</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        {createProvider === "mock" && (
                            <div class="form-control p-4 rounded-xl bg-white/5 border border-white/5 mt-2">
                                <label class="label mb-2">
                                    <span class="font-bold text-sm text-white/80">Mock Configuration</span>
                                </label>
                                <textarea name="mock_config" class="textarea textarea-bordered h-24 font-mono text-[10px] w-full bg-black/20 border-white/5 rounded-xl" defaultValue={`{"choices":[{"message":{"content":"Hello from Mock!", "role":"assistant"}}]}`} />
                            </div>
                        )}

                        <div class="flex justify-end gap-3 pt-6 border-t border-white/5">
                            <label for="create-key-modal" class="btn btn-ghost rounded-xl text-white/40 font-bold uppercase tracking-widest text-[10px]">Cancel</label>
                            <button type="submit" class="btn btn-primary px-10 rounded-xl font-bold uppercase tracking-widest text-[11px] h-11 shadow-lg shadow-primary/20">Generate Key</button>
                        </div>
                    </form>
                </div>
            </div>
        </>
    );
}

// ui/src/components/modals/CreateKeyModal.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import { X, Loader2 } from 'lucide-svelte';
  import { api } from '../../lib/api';
  
  const dispatch = createEventDispatcher();

  let providers: string[] = [];
  let loadingProviders = true;
  let submitting = false;
  let error: string | null = null;

  let formData = {
    name: '',
    provider: '',
    budget_limit: 10.0,
    budget_period: 'monthly',
    rate_limit: 60,
    rate_period: 'minute',
    is_mock: false,
    mock_config: '{}',
    expires_in_days: 30, // Default to 30 days
  };

  onMount(async () => {
    try {
      providers = await api.getProviders();
      if (providers.length > 0) {
        formData.provider = providers[0];
      }
    } catch (e: any) {
      error = "Failed to load providers: " + e.message;
    } finally {
      loadingProviders = false;
    }
  });

  async function handleSubmit() {
    submitting = true;
    error = null;

    try {
      const expiresAt = formData.expires_in_days > 0 
        ? Math.floor(Date.now() / 1000) + (formData.expires_in_days * 86400)
        : undefined;

      await api.createKey({
        name: formData.name,
        provider: formData.provider,
        budget_limit: formData.budget_limit,
        budget_period: formData.budget_period,
        rate_limit: formData.rate_limit,
        rate_period: formData.rate_period,
        is_mock: formData.is_mock,
        mock_config: formData.mock_config,
        expires_at: expiresAt,
      });

      dispatch('created');
      dispatch('close');
    } catch (e: any) {
      error = e.message;
    } finally {
      submitting = false;
    }
  }
</script>

<div class="overlay" on:click|self={() => dispatch('close')}>
  <div class="modal">
    <div class="header">
      <h2>Create New Key</h2>
      <button class="close-btn" on:click={() => dispatch('close')}>
        <X size={20} />
      </button>
    </div>

    <form on:submit|preventDefault={handleSubmit}>
      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" id="name" bind:value={formData.name} placeholder="e.g. My App Key" required />
      </div>

      <div class="form-group">
        <label for="provider">Provider</label>
        {#if loadingProviders}
          <div class="loading-input"><Loader2 class="spin" size={16} /> Loading providers...</div>
        {:else}
          <select id="provider" bind:value={formData.provider} required>
            {#each providers as p}
              <option value={p}>{p}</option>
            {/each}
          </select>
        {/if}
      </div>

      <div class="row">
        <div class="form-group">
          <label for="budget">Budget Limit ($)</label>
          <input type="number" id="budget" bind:value={formData.budget_limit} step="0.01" min="0" />
        </div>
        <div class="form-group">
          <label for="expires">Expires In (Days)</label>
          <input type="number" id="expires" bind:value={formData.expires_in_days} min="0" />
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <label for="rate">Rate Limit (req)</label>
          <input type="number" id="rate" bind:value={formData.rate_limit} min="0" />
        </div>
        <div class="form-group">
          <label for="period">Per Period</label>
          <select id="period" bind:value={formData.rate_period}>
            <option value="minute">Minute</option>
            <option value="hour">Hour</option>
            <option value="day">Day</option>
          </select>
        </div>
      </div>

      {#if error}
        <div class="error-msg">{error}</div>
      {/if}

      <div class="actions">
        <button type="button" class="btn-sec" on:click={() => dispatch('close')}>Cancel</button>
        <button type="submit" class="btn-pri" disabled={submitting}>
          {#if submitting}
            <Loader2 class="spin" size={16} /> Creating...
          {:else}
            Create Key
          {/if}
        </button>
      </div>
    </form>
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background: rgba(0, 0, 0, 0.6);
    backdrop-filter: blur(4px);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 100;
  }

  .modal {
    background: #171717;
    border: 1px solid #333;
    border-radius: 12px;
    width: 90%;
    max-width: 500px;
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
    animation: slideIn 0.2s ease-out;
  }

  @keyframes slideIn {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
  }

  .header {
    padding: 1.5rem;
    border-bottom: 1px solid #333;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  h2 {
    font-size: 1.25rem;
    font-weight: 600;
  }

  .close-btn {
    background: transparent;
    border: none;
    color: var(--color-text-muted);
    padding: 0.25rem;
  }

  .close-btn:hover {
    color: var(--color-text-main);
  }

  form {
    padding: 1.5rem;
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    flex: 1;
  }

  label {
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--color-text-muted);
  }

  .loading-input {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: var(--color-text-muted);
    font-size: 0.875rem;
  }

  .row {
    display: flex;
    gap: 1rem;
  }

  .actions {
    display: flex;
    justify-content: flex-end;
    gap: 0.75rem;
    margin-top: 1rem;
  }

  .btn-pri {
    background: var(--color-primary);
    color: white;
    border: none;
    padding: 0.5rem 1rem;
    border-radius: var(--radius);
    font-weight: 500;
    display: flex;
    align-items: center;
    gap: 0.5rem;
    transition: background 0.2s;
  }

  .btn-pri:hover:not(:disabled) {
    background: var(--color-primary-hover);
  }

  .btn-pri:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .btn-sec {
    background: transparent;
    color: var(--color-text-main);
    border: 1px solid var(--color-border);
    padding: 0.5rem 1rem;
    border-radius: var(--radius);
    font-weight: 500;
  }

  .btn-sec:hover {
    background: var(--color-surface-hover);
  }

  .error-msg {
    color: var(--color-danger);
    font-size: 0.875rem;
    background: rgba(239, 68, 68, 0.1);
    padding: 0.75rem;
    border-radius: var(--radius);
  }
  
  .spin {
    animation: spin 1s linear infinite;
  }
  
  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }
</style>
